name: 'build docker image and deploy GitHub Pages'

on:
  push:
    tags:
      - '*'  # Trigger เมื่อมีการ push tag ใดๆ

jobs:
  release-docker-image-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Extract tag name
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Verify extracted tag
        run: echo "Using TAG_NAME=${{ env.TAG_NAME }}"

      - name: Build and push Docker image
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: githubaction
          registry: ghcr.io/naruapon
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          tags: ${{ env.TAG_NAME }}, latest

  deploy-github-pages:
    needs: release-docker-image-job  # รอให้ build และ push Docker image สำเร็จก่อน
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Build static site
        run: |
          mkdir -p public
          echo "<h1>GitHub Pages Deployed Successfully</h1>" > public/index.html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
